"use client";
import { useEffect, useMemo, useState } from "react";
type User = { id: string; email: string; name?: string; role: "user" | "admin" };
type Bet = { _id: string; creatorId: string; participantIds: string[]; participants?: { email: string; name?: string }[]; condition: string; wager: string; deadline: string; status: "open" | "completed" | "cancelled" | "unresolved"; resolutionNote?: string };
type Activity = { _id: string; message: string; createdAt: string };
const dateTime = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const label = (bet: Bet) => bet.status === "open" && new Date(bet.deadline) < new Date() ? "overdue" : bet.status;

export default function Dashboard({ user }: { user: User }) {
  const [bets, setBets] = useState<Bet[]>([]); const [activity, setActivity] = useState<Activity[]>([]); const [tab, setTab] = useState<"active" | "history">("active"); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState<Bet | null>(null); const [resolutionNote, setResolutionNote] = useState(""); const [error, setError] = useState("");
  const refresh = async () => { const [b, a] = await Promise.all([fetch("/api/bets").then(r => r.json()), fetch("/api/activities").then(r => r.json())]); setBets(b.bets ?? []); setActivity(a.activities ?? []); };
  useEffect(() => { refresh(); }, []);
  const shown = useMemo(() => bets.filter(b => tab === "active" ? b.status === "open" : b.status !== "open"), [bets, tab]);
  async function create(form: HTMLFormElement) { setError(""); const fd = new FormData(form); const response = await fetch("/api/bets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ condition: fd.get("condition"), wager: fd.get("wager"), deadline: new Date(String(fd.get("deadline"))).toISOString(), participantEmails: String(fd.get("participants")).split(",").map(x => x.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) return setError(data.error || "Could not create bet"); form.reset(); setShowForm(false); refresh(); }
  async function close(status: "completed" | "cancelled" | "unresolved") { if (!selected) return; const r = await fetch(`/api/bets/${selected._id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, resolutionNote }) }); if (!r.ok) return setError((await r.json()).error); setResolutionNote(""); setSelected(null); refresh(); }
  return <main className="shell"><header><a className="brand" href="/">STAKEOUT</a><div className="profile"><span>{user.name || user.email}</span>{user.role === "admin" && <a href="/admin">Admin</a>}</div></header>
    <section className="hero"><div><p className="eyebrow">YOUR BETS</p><h1>Keep the score.</h1><p>Every friendly wager, clear and accounted for.</p></div><button className="primary" onClick={() => setShowForm(true)}>+ New bet</button></section>
    {error && <p className="error">{error}</p>}
    {showForm && <section className="form-card"><div className="row"><h2>Make a new bet</h2><button className="text-button" onClick={() => setShowForm(false)}>Close</button></div><form onSubmit={e => { e.preventDefault(); create(e.currentTarget); }}><label>What needs to happen?<textarea name="condition" required minLength={3} placeholder="The exact condition you both agree to" /></label><label>What’s at stake?<input name="wager" required minLength={2} placeholder="Loser brings coffee next week" /></label><label>Deadline<input name="deadline" type="datetime-local" required /></label><label>Friends’ registered emails <small>Separate multiple addresses with commas.</small><input name="participants" type="text" required placeholder="friend@example.com" /></label><button className="primary">Create bet</button></form></section>}
    <nav className="tabs"><button className={tab === "active" ? "active" : ""} onClick={() => setTab("active")}>Active <span>{bets.filter(b => b.status === "open").length}</span></button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>History</button></nav>
    <section className="grid"><div className="bets">{shown.length ? shown.map(bet => <button className={`bet-card ${label(bet)}`} key={bet._id} onClick={() => setSelected(bet)}><div className="card-top"><span className={`badge ${label(bet)}`}>{label(bet)}</span><time>{dateTime(bet.deadline)}</time></div><h2>{bet.condition}</h2><p className="wager">{bet.wager}</p><p className="people">with {bet.participants?.filter(p => p?.email !== user.email).map(p => p?.name || p?.email).join(", ") || "you"}</p></button>) : <div className="empty">No {tab} bets yet.</div>}</div><aside><p className="eyebrow">RECENT ACTIVITY</p>{activity.length ? activity.slice(0, 6).map(a => <div className="activity" key={a._id}><p>{a.message}</p><time>{dateTime(a.createdAt)}</time></div>) : <p className="muted">Your updates will appear here.</p>}</aside></section>
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="modal" onClick={e => e.stopPropagation()}><div className="row"><span className={`badge ${label(selected)}`}>{label(selected)}</span><button className="text-button" onClick={() => setSelected(null)}>Close</button></div><h2>{selected.condition}</h2><p className="wager">{selected.wager}</p><p>Due {dateTime(selected.deadline)}</p>{selected.resolutionNote && <p className="note">{selected.resolutionNote}</p>}{selected.status === "open" && selected.creatorId === user.id && <><label className="resolution">Outcome note <small>Optional; visible to participants.</small><textarea value={resolutionNote} onChange={e => setResolutionNote(e.target.value)} placeholder="What was the outcome?" /></label><div className="actions"><button onClick={() => close("completed")}>Complete</button><button onClick={() => close("unresolved")}>Unresolved</button><button className="danger" onClick={() => close("cancelled")}>Cancel bet</button></div></>}</section></div>}
  </main>;
}
